
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Search from '../components/Search'
import styles from '../styles/Home.module.css'
import 'semantic-ui-css/semantic.min.css'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function trending() {
    return (
        <div className={styles.container}>
        <Head>
          <title>Search Result</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/drawing.svg" />
        </Head>


        <Navbar />

        <main className={styles.main}>

            <Search />

        
       </main>









        <Footer />


            
        </div>
    )
}
